### ISSUE TITLE
문제에 대한 내용 및 해석을 자세하게 적어주세요...

### ISSUE THREAD

**Issue by gihyeoon** [chihungim/AlgorithmCodeforces#2]
문제에 대한 내용, 해석이 명확하게 표시되어 있지 않습니다.. 깨져있거나 확실하지 않아요...

**Comment by chihungim** [comment]
파이어 폭스를 써보세요

**Comment by gihyeoon** [comment]
Firefoxのシェアは韓国で1.78％と最も低いです。ところでFirefoxを利用すれば正しく見えるというのは正しいとは思いません。
